# Generated by Django 5.2.4 on 2025-08-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerrooms', '0002_alter_room_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/'),
        ),
    ]
