# Generated by Django 5.2.4 on 2025-08-10 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerrooms', '0003_room_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
