# Generated by Django 5.2.4 on 2025-08-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomrequest',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='roomrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
